name: immunet_fig3_tf
channels:
  - defaults
dependencies:
  - python=3.6.9
  - pip=21.2.2
  - pip:
    - numpy==1.19.1
    - scipy==1.5.0
    - pandas==1.1.5
    - tqdm==4.64.1
    - scikit-image==0.17.2  
    - keras==2.3.1
    - tensorflow-gpu==1.14.0
    - csbdeep==0.6.0
    - h5py==2.10.0
    - tifffile==2020.9.3
