name: immunet_fig4_tf
channels:
  - defaults
dependencies:
  - python=3.6.9
  - pip=21.2.2
  - pip:
    - imagecodecs==2020.5.30
    - numpy==1.19.1
    - keras==2.3.1
    - tensorflow-gpu==1.14.0
    - Pillow==7.1.2
    - scipy==1.5.0
    - tifffile==2020.9.3
    - scikit-image==0.17.2
    - networkx==2.5.1
    - pandas==1.1.5
    - Shapely==1.8.5.post1
    - csbdeep==0.6.0
    - h5py==2.10.0
