install.packages("polycor", repos = "https://cloud.r-project.org")
install.packages("remotes", repos = "https://cloud.r-project.org")
remotes::install_version("cowplot", "1.1.1", repos = "https://cloud.r-project.org", upgrade="always")
remotes::install_version("dplyr", "1.1.4", repos = "https://cloud.r-project.org", upgrade="always")
remotes::install_version("ggplot2", "3.5.0", repos = "https://cloud.r-project.org", upgrade="always")
remotes::install_version("irr", "0.84.1", repos = "https://cloud.r-project.org", upgrade="always")
remotes::install_version("readr", "2.1.5", repos = "https://cloud.r-project.org", upgrade="always")
remotes::install_version("tidyr", "1.3.1", repos = "https://cloud.r-project.org", upgrade="always")
remotes::install_version("boot", "1.3-28.1", repos = "https://cloud.r-project.org", upgrade="always")
remotes::install_version("stringr", "1.5.1", repos = "https://cloud.r-project.org", upgrade="always")
remotes::install_version("RColorBrewer", "1.1-3", repos = "https://cloud.r-project.org", upgrade="always")
remotes::install_version("scales", "1.3.0", repos = "https://cloud.r-project.org", upgrade="always")
remotes::install_version("egg", "0.4.5", repos = "https://cloud.r-project.org", upgrade="always")
remotes::install_version("gridExtra", "2.3", repos = "https://cloud.r-project.org", upgrade="always")
remotes::install_version("hexbin", "1.28.5 ", repos = "https://cloud.r-project.org", upgrade="always")